### ISSUE TITLE
A handful of suggestions

### ISSUE THREAD

**Issue by mkanski** [andeplane/atomify#74]
Hi, 
Sorry for a late response, but recently I have quite a lot of things going on. My ideas are below. I don't know if all of them can be implemented, so I didn't create separate threads. Let me know, if you want me to elaborate on the ideas or bug reports.

Ideas:

- [ ] manual describing Atomify commands (#/camera, #/atom, etc.)
- [ ] orthographic visualization mode
- [ ] add scale bar (or grid) to the visualization window
- [ ] add units to axis titles in plots
- [ ] use a shortcut to change mouse mode, e.g. after clicking "T", mouse pans the view instead of rotating it (similar as in VMD)
- [ ] plots for variables

- [ ] a way of changing simulation parameters from the visualization window, e.g. a slider which would change the target temperature of a thermostat
- [ ] parallel simulations

Bug reports:

- [ ] If you start a simulation, pause it, then click on "New simulation" and write any number in the "Name" field, a popup will appear saying "Setting simulation speed to X."
- [ ] The y-axes of plots have wrong titles, for example a plot for "thermo_temp" is titled "Potential energy"

**Comment by andeplane** [comment]
Thanks a lot for great input. Could you add these as separate issues, so it's easier track each one. I see many here that makes a lot of sense!

**Comment by mkanski** [comment]
Done. :)
